require: rubocop-rails

AllCops:
  Exclude:
    - db/schema.rb

Documentation:
  Enabled: false

Layout/ClassStructure:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Exclude:
    - app/views/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Max: 15
  Exclude:

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - config/**/*
    - spec/**/*
    - app/admin/**/*

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  CountComments: false 
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 6

Metrics/MethodLength:
  CountComments: false
  Max: 24

Metrics/ModuleLength:
  CountComments: false
  Max: 200

Metrics/LineLength:
  Max: 100
  AllowURI: true
  Exclude:
  URISchemes:
    - http
    - https

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 12

Rails:
  Enabled: true

Rails/Delegate:
  Enabled: true
  Exclude:

Rails/FilePath:
  Enabled: false

Rails/SaveBang:
  Enabled: true
  Exclude:

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ExpandPathArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/ReturnNil:
  Enabled: true

Style/StringLiterals:
  Exclude: